title: SimpleText@CLEF-2023 
email: contact@simpletext-project.com
description: >- # this means to ignore newlines until "baseurl:"
        SimpleText is a track organised as part of <a href="https://clef2023.clef-initiative.eu/index.php">CLEF-2023 conference</a>, 
        initiated by <a href="http://www.clef-initiative.eu/">CLEF initiative</a>.
url: "http://simpletext-project.com/2023/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SimpletextW
github_username:  simpletext-madics
